import type {Address, Category, Coupon, Notification, PaymentMethod, Product, Review, Store} from '../types/domain.js';

export const categories: Category[] = [
  {
    id: 'cat-burgers',
    name: 'Burgers',
    slug: 'burgers',
    icon: 'Burger',
    color: '#6C47FF',
    type: 'restaurant',
    description: 'Premium burgers, crispy sides, and fast comfort food.'
  },
  {
    id: 'cat-chicken',
    name: 'Chicken',
    slug: 'chicken',
    icon: 'Drumstick',
    color: '#FFB703',
    type: 'restaurant',
    description: 'Fried chicken, wings, wraps, and family buckets.'
  },
  {
    id: 'cat-coffee',
    name: 'Coffee',
    slug: 'coffee',
    icon: 'Coffee',
    color: '#00C897',
    type: 'restaurant',
    description: 'Coffee, pastries, breakfast, and cold drinks.'
  },
  {
    id: 'cat-pizza',
    name: 'Pizza',
    slug: 'pizza',
    icon: 'Pizza',
    color: '#FF6B6B',
    type: 'restaurant',
    description: 'Fresh pizza, sides, dips, and late-night favorites.'
  },
  {
    id: 'cat-groceries',
    name: 'Groceries',
    slug: 'groceries',
    icon: 'ShoppingBasket',
    color: '#2F80ED',
    type: 'supermarket',
    description: 'Fresh produce, pantry, dairy, and household essentials.'
  },
  {
    id: 'cat-organic',
    name: 'Organic',
    slug: 'organic',
    icon: 'Leaf',
    color: '#16A34A',
    type: 'supermarket',
    description: 'Organic staples, healthy snacks, and fresh market finds.'
  },
  {
    id: 'cat-convenience',
    name: 'Convenience',
    slug: 'convenience',
    icon: 'Zap',
    color: '#F97316',
    type: 'convenience',
    description: 'Snacks, drinks, pharmacy basics, and quick top-ups.'
  },
  {
    id: 'cat-deals',
    name: 'Flash Deals',
    slug: 'flash-deals',
    icon: 'BadgePercent',
    color: '#EC4899',
    type: 'all',
    description: 'Limited-time offers across restaurants and supermarkets.'
  }
];

export const stores: Store[] = [
  {
    id: 'store-mcdonalds',
    slug: 'mcdonalds',
    name: "McDonald's",
    type: 'restaurant',
    cuisine: 'Burgers and fries',
    category: 'Burgers',
    description: 'Iconic burgers, fries, McCafe drinks, and fast family meals delivered hot.',
    logoUrl: 'https://logo.clearbit.com/mcdonalds.com',
    heroImageUrl: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&w=1400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1619881590738-a111d176d906?auto=format&fit=crop&w=1600&q=80',
    rating: 4.6,
    reviewCount: 18240,
    deliveryTimeMinutes: 18,
    deliveryFeeCents: 199,
    minimumOrderCents: 900,
    distanceKm: 1.2,
    priceLevel: '$',
    tags: ['Fast delivery', 'Family meals', 'McCafe'],
    isFeatured: true,
    isOpen: true
  },
  {
    id: 'store-kfc',
    slug: 'kfc',
    name: 'KFC',
    type: 'restaurant',
    cuisine: 'Fried chicken',
    category: 'Chicken',
    description: 'Crispy chicken buckets, sandwiches, tenders, and signature sides.',
    logoUrl: 'https://logo.clearbit.com/kfc.com',
    heroImageUrl: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?auto=format&fit=crop&w=1400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1606755962773-d324e2e1a74d?auto=format&fit=crop&w=1600&q=80',
    rating: 4.5,
    reviewCount: 12980,
    deliveryTimeMinutes: 24,
    deliveryFeeCents: 249,
    minimumOrderCents: 1000,
    distanceKm: 2.1,
    priceLevel: '$$',
    tags: ['Buckets', 'Spicy', 'Late night'],
    isFeatured: true,
    isOpen: true
  },
  {
    id: 'store-burger-king',
    slug: 'burger-king',
    name: 'Burger King',
    type: 'restaurant',
    cuisine: 'Flame-grilled burgers',
    category: 'Burgers',
    description: 'Flame-grilled burgers, plant-based options, fries, and shakes.',
    logoUrl: 'https://logo.clearbit.com/bk.com',
    heroImageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=1600&q=80',
    rating: 4.4,
    reviewCount: 9340,
    deliveryTimeMinutes: 22,
    deliveryFeeCents: 199,
    minimumOrderCents: 900,
    distanceKm: 1.8,
    priceLevel: '$',
    tags: ['Flame grilled', 'Plant-based', 'Value'],
    isFeatured: false,
    isOpen: true
  },
  {
    id: 'store-starbucks',
    slug: 'starbucks',
    name: 'Starbucks',
    type: 'restaurant',
    cuisine: 'Coffee and bakery',
    category: 'Coffee',
    description: 'Handcrafted coffee, matcha, refreshers, breakfast sandwiches, and pastries.',
    logoUrl: 'https://logo.clearbit.com/starbucks.com',
    heroImageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1600&q=80',
    rating: 4.8,
    reviewCount: 21410,
    deliveryTimeMinutes: 16,
    deliveryFeeCents: 149,
    minimumOrderCents: 800,
    distanceKm: 0.9,
    priceLevel: '$$',
    tags: ['Coffee', 'Breakfast', 'Rewards'],
    isFeatured: true,
    isOpen: true
  },
  {
    id: 'store-pizza-hut',
    slug: 'pizza-hut',
    name: 'Pizza Hut',
    type: 'restaurant',
    cuisine: 'Pizza and sides',
    category: 'Pizza',
    description: 'Pan pizzas, melt deals, pasta bakes, wings, and desserts for groups.',
    logoUrl: 'https://logo.clearbit.com/pizzahut.com',
    heroImageUrl: 'https://images.unsplash.com/photo-1593504049359-74330189a345?auto=format&fit=crop&w=1400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=1600&q=80',
    rating: 4.3,
    reviewCount: 8080,
    deliveryTimeMinutes: 29,
    deliveryFeeCents: 299,
    minimumOrderCents: 1200,
    distanceKm: 2.6,
    priceLevel: '$$',
    tags: ['Group deals', 'Pizza', 'Wings'],
    isFeatured: false,
    isOpen: true
  },
  {
    id: 'store-subway',
    slug: 'subway',
    name: 'Subway',
    type: 'restaurant',
    cuisine: 'Subs and salads',
    category: 'Sandwiches',
    description: 'Custom subs, wraps, salads, cookies, and lighter lunch options.',
    logoUrl: 'https://logo.clearbit.com/subway.com',
    heroImageUrl: 'https://images.unsplash.com/photo-1619096252214-ef06c45683e3?auto=format&fit=crop&w=1400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=1600&q=80',
    rating: 4.4,
    reviewCount: 6760,
    deliveryTimeMinutes: 20,
    deliveryFeeCents: 199,
    minimumOrderCents: 850,
    distanceKm: 1.6,
    priceLevel: '$',
    tags: ['Customizable', 'Lunch', 'Fresh'],
    isFeatured: false,
    isOpen: true
  },
  {
    id: 'store-carrefour',
    slug: 'carrefour',
    name: 'Carrefour',
    type: 'supermarket',
    cuisine: 'Supermarket',
    category: 'Groceries',
    description: 'Full-basket grocery delivery with produce, pantry, home care, and baby essentials.',
    logoUrl: 'https://logo.clearbit.com/carrefour.com',
    heroImageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1600&q=80',
    rating: 4.7,
    reviewCount: 15420,
    deliveryTimeMinutes: 35,
    deliveryFeeCents: 349,
    minimumOrderCents: 1800,
    distanceKm: 3.1,
    priceLevel: '$$',
    tags: ['Weekly shop', 'Fresh produce', 'Household'],
    isFeatured: true,
    isOpen: true
  },
  {
    id: 'store-lidl',
    slug: 'lidl',
    name: 'Lidl',
    type: 'supermarket',
    cuisine: 'Discount grocery',
    category: 'Groceries',
    description: 'Great-value groceries, bakery favorites, dairy, frozen goods, and fresh produce.',
    logoUrl: 'https://logo.clearbit.com/lidl.com',
    heroImageUrl: 'https://images.unsplash.com/photo-1543168256-418811576931?auto=format&fit=crop&w=1400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1600&q=80',
    rating: 4.5,
    reviewCount: 11260,
    deliveryTimeMinutes: 32,
    deliveryFeeCents: 299,
    minimumOrderCents: 1500,
    distanceKm: 2.8,
    priceLevel: '$',
    tags: ['Value', 'Bakery', 'Weekly essentials'],
    isFeatured: false,
    isOpen: true
  },
  {
    id: 'store-aldi',
    slug: 'aldi',
    name: 'Aldi',
    type: 'supermarket',
    cuisine: 'Everyday grocery',
    category: 'Groceries',
    description: 'Affordable everyday staples, seasonal specials, produce, and private-label favorites.',
    logoUrl: 'https://logo.clearbit.com/aldi.com',
    heroImageUrl: 'https://images.unsplash.com/photo-1588964895597-cfccd6e2dbf9?auto=format&fit=crop&w=1400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=1600&q=80',
    rating: 4.6,
    reviewCount: 9840,
    deliveryTimeMinutes: 34,
    deliveryFeeCents: 299,
    minimumOrderCents: 1500,
    distanceKm: 3.4,
    priceLevel: '$',
    tags: ['Budget', 'Produce', 'Private label'],
    isFeatured: false,
    isOpen: true
  },
  {
    id: 'store-rewe',
    slug: 'rewe',
    name: 'REWE',
    type: 'supermarket',
    cuisine: 'Fresh supermarket',
    category: 'Groceries',
    description: 'Premium fresh food, organic ranges, drinks, bakery, and household essentials.',
    logoUrl: 'https://logo.clearbit.com/rewe.de',
    heroImageUrl: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?auto=format&fit=crop&w=1400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1601599561213-832382fd07ba?auto=format&fit=crop&w=1600&q=80',
    rating: 4.8,
    reviewCount: 13730,
    deliveryTimeMinutes: 30,
    deliveryFeeCents: 249,
    minimumOrderCents: 1600,
    distanceKm: 2.4,
    priceLevel: '$$',
    tags: ['Organic', 'Fresh bakery', 'Premium'],
    isFeatured: true,
    isOpen: true
  }
];

export const products: Product[] = [
  {
    id: 'prod-big-mac-menu',
    storeId: 'store-mcdonalds',
    restaurantId: 'store-mcdonalds',
    categoryId: 'cat-burgers',
    category: 'Burgers',
    name: 'Big Mac Meal',
    description: 'Big Mac, medium fries, and a chilled soft drink.',
    priceCents: 1099,
    originalPriceCents: 1299,
    discountPercent: 15,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',
    calories: 1080,
    rating: 4.8,
    isAvailable: true,
    isPopular: true
  },
  {
    id: 'prod-mccafe-latte',
    storeId: 'store-mcdonalds',
    restaurantId: 'store-mcdonalds',
    categoryId: 'cat-coffee',
    category: 'Coffee',
    name: 'McCafe Iced Latte',
    description: 'Espresso, milk, and ice with a smooth vanilla finish.',
    priceCents: 429,
    imageUrl: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80',
    calories: 180,
    rating: 4.5,
    isAvailable: true,
    isPopular: false
  },
  {
    id: 'prod-kfc-bucket',
    storeId: 'store-kfc',
    restaurantId: 'store-kfc',
    categoryId: 'cat-chicken',
    category: 'Chicken',
    name: 'Original Recipe Bucket',
    description: 'Eight pieces of signature chicken with fries and gravy.',
    priceCents: 2199,
    originalPriceCents: 2499,
    discountPercent: 12,
    imageUrl: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?auto=format&fit=crop&w=900&q=80',
    calories: 2400,
    rating: 4.7,
    isAvailable: true,
    isPopular: true
  },
  {
    id: 'prod-kfc-zinger',
    storeId: 'store-kfc',
    restaurantId: 'store-kfc',
    categoryId: 'cat-chicken',
    category: 'Chicken',
    name: 'Zinger Burger Box',
    description: 'Spicy chicken burger with fries, coleslaw, and a drink.',
    priceCents: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1606755962773-d324e2e1a74d?auto=format&fit=crop&w=900&q=80',
    calories: 980,
    rating: 4.6,
    isAvailable: true,
    isPopular: true
  },
  {
    id: 'prod-whopper-meal',
    storeId: 'store-burger-king',
    restaurantId: 'store-burger-king',
    categoryId: 'cat-burgers',
    category: 'Burgers',
    name: 'Whopper Meal',
    description: 'Flame-grilled Whopper with fries and a refillable drink.',
    priceCents: 1149,
    imageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=900&q=80',
    calories: 1110,
    rating: 4.6,
    isAvailable: true,
    isPopular: true
  },
  {
    id: 'prod-starbucks-caramel-macchiato',
    storeId: 'store-starbucks',
    restaurantId: 'store-starbucks',
    categoryId: 'cat-coffee',
    category: 'Coffee',
    name: 'Caramel Macchiato',
    description: 'Steamed milk, espresso, vanilla syrup, and caramel drizzle.',
    priceCents: 575,
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80',
    calories: 250,
    rating: 4.9,
    isAvailable: true,
    isPopular: true
  },
  {
    id: 'prod-starbucks-croissant',
    storeId: 'store-starbucks',
    restaurantId: 'store-starbucks',
    categoryId: 'cat-coffee',
    category: 'Coffee',
    name: 'Butter Croissant',
    description: 'Flaky French-style croissant baked until golden.',
    priceCents: 349,
    imageUrl: 'https://images.unsplash.com/photo-1620146344904-097a0002d797?auto=format&fit=crop&w=900&q=80',
    calories: 260,
    rating: 4.7,
    isAvailable: true,
    isPopular: false
  },
  {
    id: 'prod-pizza-hut-margherita',
    storeId: 'store-pizza-hut',
    restaurantId: 'store-pizza-hut',
    categoryId: 'cat-pizza',
    category: 'Pizza',
    name: 'Margherita Pan Pizza',
    description: 'Classic tomato, mozzarella, basil, and signature pan crust.',
    priceCents: 1399,
    imageUrl: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=900&q=80',
    calories: 1480,
    rating: 4.4,
    isAvailable: true,
    isPopular: true
  },
  {
    id: 'prod-subway-italian-bmt',
    storeId: 'store-subway',
    restaurantId: 'store-subway',
    categoryId: 'cat-burgers',
    category: 'Sandwiches',
    name: 'Italian B.M.T.',
    description: 'Salami, pepperoni, ham, cheese, crisp vegetables, and house sauce.',
    priceCents: 899,
    imageUrl: 'https://images.unsplash.com/photo-1619096252214-ef06c45683e3?auto=format&fit=crop&w=900&q=80',
    calories: 760,
    rating: 4.5,
    isAvailable: true,
    isPopular: false
  },
  {
    id: 'prod-carrefour-berries',
    storeId: 'store-carrefour',
    restaurantId: 'store-carrefour',
    categoryId: 'cat-groceries',
    category: 'Fresh Produce',
    name: 'Mixed Berries Pack',
    description: 'Strawberries, blueberries, and raspberries washed and ready to serve.',
    priceCents: 699,
    originalPriceCents: 849,
    discountPercent: 18,
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=900&q=80',
    weight: '450 g',
    rating: 4.8,
    isAvailable: true,
    isPopular: true
  },
  {
    id: 'prod-carrefour-avocado',
    storeId: 'store-carrefour',
    restaurantId: 'store-carrefour',
    categoryId: 'cat-groceries',
    category: 'Fresh Produce',
    name: 'Ready-to-Eat Avocados',
    description: 'Two ripe Hass avocados selected for same-day use.',
    priceCents: 499,
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=900&q=80',
    weight: '2 pcs',
    rating: 4.7,
    isAvailable: true,
    isPopular: false
  },
  {
    id: 'prod-lidl-bakery-box',
    storeId: 'store-lidl',
    restaurantId: 'store-lidl',
    categoryId: 'cat-groceries',
    category: 'Bakery',
    name: 'Fresh Bakery Box',
    description: 'Croissants, pretzels, seeded rolls, and pain au chocolat.',
    priceCents: 799,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80',
    weight: '8 pcs',
    rating: 4.6,
    isAvailable: true,
    isPopular: true
  },
  {
    id: 'prod-aldi-organic-eggs',
    storeId: 'store-aldi',
    restaurantId: 'store-aldi',
    categoryId: 'cat-organic',
    category: 'Organic',
    name: 'Organic Free-Range Eggs',
    description: 'Large free-range eggs from certified organic farms.',
    priceCents: 529,
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=900&q=80',
    weight: '10 pcs',
    rating: 4.8,
    isAvailable: true,
    isPopular: true
  },
  {
    id: 'prod-rewe-oat-milk',
    storeId: 'store-rewe',
    restaurantId: 'store-rewe',
    categoryId: 'cat-organic',
    category: 'Organic',
    name: 'Barista Oat Milk',
    description: 'Creamy oat drink for espresso, cereal, smoothies, and baking.',
    priceCents: 279,
    originalPriceCents: 349,
    discountPercent: 20,
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=900&q=80',
    weight: '1 L',
    rating: 4.9,
    isAvailable: true,
    isPopular: true
  },
  {
    id: 'prod-rewe-sushi-box',
    storeId: 'store-rewe',
    restaurantId: 'store-rewe',
    categoryId: 'cat-groceries',
    category: 'Ready Meals',
    name: 'Fresh Salmon Sushi Box',
    description: 'Nigiri and maki selection packed fresh for lunch or dinner.',
    priceCents: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?auto=format&fit=crop&w=900&q=80',
    weight: '360 g',
    rating: 4.7,
    isAvailable: true,
    isPopular: false
  }
];

export const coupons: Coupon[] = [
  {
    id: 'coupon-welcome',
    code: 'WELCOME25',
    title: '25% off your first order',
    description: 'Use on restaurants or groceries above EUR 18.',
    discountPercent: 25,
    minimumOrderCents: 1800,
    expiresAt: '2026-12-31T23:59:00.000Z',
    isActive: true
  },
  {
    id: 'coupon-grocery',
    code: 'FRESH15',
    title: 'Fresh grocery run',
    description: 'Save 15% on supermarket baskets above EUR 35.',
    discountPercent: 15,
    minimumOrderCents: 3500,
    expiresAt: '2026-09-30T23:59:00.000Z',
    isActive: true
  }
];

export const demoAddresses: Address[] = [
  {
    id: 'addr-home',
    userId: 'user-customer',
    label: 'Home',
    line1: 'Ledra Street 42',
    line2: 'Apt 5B',
    city: 'Nicosia',
    postalCode: '1011',
    instructions: 'Ring twice, leave at reception if unavailable.',
    isDefault: true
  },
  {
    id: 'addr-office',
    userId: 'user-customer',
    label: 'Office',
    line1: 'Makariou Avenue 1',
    city: 'Nicosia',
    postalCode: '1065',
    instructions: 'Meet at lobby coffee bar.',
    isDefault: false
  }
];

export const demoPayments: PaymentMethod[] = [
  {
    id: 'pay-visa',
    userId: 'user-customer',
    brand: 'Visa',
    last4: '4242',
    label: 'Personal card',
    isDefault: true
  },
  {
    id: 'pay-apple',
    userId: 'user-customer',
    brand: 'Apple Pay',
    last4: '0000',
    label: 'Apple Pay',
    isDefault: false
  }
];

export const demoNotifications: Notification[] = [
  {
    id: 'notif-order',
    userId: 'user-customer',
    title: 'Your Starbucks order is preparing',
    body: 'The store accepted your order and your rider will be assigned shortly.',
    type: 'order',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString()
  },
  {
    id: 'notif-offer',
    userId: 'user-customer',
    title: 'Flash grocery deals are live',
    body: 'Save on fresh berries, oat milk, bakery boxes, and more today.',
    type: 'offer',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 48).toISOString()
  }
];

export const reviews: Review[] = [
  {
    id: 'review-starbucks-1',
    storeId: 'store-starbucks',
    userId: 'user-customer',
    userName: 'Casey Customer',
    rating: 5,
    body: 'Coffee arrived sealed, warm, and faster than expected.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString()
  },
  {
    id: 'review-rewe-1',
    storeId: 'store-rewe',
    userId: 'user-customer',
    userName: 'Casey Customer',
    rating: 5,
    body: 'Produce quality was excellent and substitutions were sensible.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString()
  }
];
